#!/bin/bash
student="Sarah"

echo "Hello ${student}"

# change the first character to lower case
echo "Hello ${student,}"

# change the all characters to lower case
echo "Hello ${student,,}"

# change the first character to upper case
echo "Hello ${student^}"

# change the all charactes to upper case
echo "Hello ${student^^}"

# To get the number of characters a varable containes
echo "The number of characters in ${student} is ${#student}"

# slice opration takes the form of ${parameter:offset:length}
echo ${student:1:3} #ara
echo ${student:0:3} #Sar
echo ${student:1} #arah
echo ${student: -2 : 2} #ah
length=${#student}

echo ${length}

echo ${student:0:4} #Sara

echo ${student: -4} #arah




exit 0