#!/bin/bash
student="Sarah"

echo "Hello ${student}"

# change the first character to lower case
echo "Hello ${student,}"

# change the all characters to lower case
echo "Hello ${student,,}"

# change the first character to upper case
echo "Hello ${student^}"

# change the all charactes to upper case
echo "Hello ${student^^}"

# To get the number of characters a varable containes
echo "The number of characters in ${student} is ${#student}"

# slice opration takes the form of ${parameter:offset:length}
echo ${student:1:3} #ara
echo ${student:0:3} #Sar
echo ${student:1} #arah
echo ${student: -2 : 2} #ah

length=${#student}

echo $length

echo ${student:0:4} #Sara

echo ${student: -4} #arah


################################
# command substitution
################################
time=$(date +%H:%M:%S)
echo "the time right now is $time"

################################
# Arithmetic expansion
################################

echo $((length + 1))

echo ${student:  0  : $((length - 1 ))} #Sara

x=5 y=2

echo $((x + y))

echo $((x / y))  # returns an integer 2

echo $((x * y))

echo $((x ** y))

echo $((x % y))

exit 0